Verify customer screen
pgahq/face-finder-frontend pull request #1
Opened 2021-11-06 11:55 UTC by imcvampire

2021-11-06 14:30 UTC, jsw324 requested changes
A few questions:

- Do we need/want a way to handle users that are already logged in?
- Do we want this to happen at the root `/` URL or should it occur at a different path?

Please feel free to take liberties with the design, don't feel like you need to adhere to that flow I sent.

2021-11-06 14:30 UTC, jsw324 commented on src/components/index.js
> +export { default as BottomContainer } from './BottomContainer'
let's remove this file as it'll grow out of control. We can import the components we need directly from the component file

2021-11-06 14:30 UTC, jsw324 commented on src/components/BottomContainer/index.js
> +const BottomContainer = styled('div')({
this maybe belongs in an 'atoms' folder within components folder so we can have one file for all the little styled components we create.  Not a deal breaker just a thought.  The intent of the components folder is to have a repository of all our reusable components -- something to think about is how easy it'll be to find items and reason about as it grows.

2021-11-06 14:30 UTC, jsw324 commented on src/lib/apollo/index.js
> +    const uploadLink = createUploadLink({
😎

2021-11-06 14:30 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +import { BottomContainer } from '../../components'
```suggestion
import BottomContainer from '../../components/BottomContainer'
```

2021-11-06 14:30 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +    if (currentPage === INFO_PAGE) {
this is confusing. I think we can have a better flow to these components.

We want to avoid nested `if` statements as they're a source of confusion for other developers

2021-11-06 14:30 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +} from '@mui/material'
lets import each of these components individually

`import Button from '@mui/material/Button`

Reason being we'll be importing the entire library by doing it that way, especially in development: https://mui.com/guides/minimizing-bundle-size/#development-environment

2021-11-06 14:30 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +          <Box mt={1}>
this should be it's own component.  If you feel we can reuse it let's move it to `components/photo_uploader`

2021-11-06 14:30 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +          <Box>
this should be it's own component. We can move it to a file in this directory.

2021-11-06 14:32 UTC, imcvampire commented on src/pages/VerifyConsumer/index.js
> +    if (currentPage === INFO_PAGE) {
What do you think if we redirect to a new route?

2021-11-06 14:34 UTC, imcvampire commented on src/pages/VerifyConsumer/index.js
> +} from '@mui/material'
What do you think if we use the babel plugin for that? https://mui.com/guides/minimizing-bundle-size/#option-2

2021-11-06 14:38 UTC, imcvampire commented
> A few questions:
> 
> * Do we need/want a way to handle users that are already logged in?
> * Do we want this to happen at the root `/` URL or should it occur at a different path?
> 
> Please feel free to take liberties with the design, don't feel like you need to adhere to that flow I sent.

1. IIRC, we don't need to remember the authentication. But if we need it, we can store it securely on the cookie. 
2. If there is no other screen (e.g., Introduction, ...), I think we can use `/`.

2021-11-06 14:42 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +    if (currentPage === INFO_PAGE) {
i think that could work - the most important thing is to avoid confusing logic with many 'if' clauses.  We can do that through separating the components or a new route.

I'm not sure we're getting any benefits to a new route as we're never going to send a user directly to step 2.

Maybe [this component ](https://mui.com/components/steppers/) could work?

2021-11-06 14:42 UTC, imcvampire commented on src/components/BottomContainer/index.js
> +const BottomContainer = styled('div')({
Personally, I flat all components but it's hard to classify client-parent components and I don't want to re-order if a new use case is introduced. 

But I think it's great if we follow your suggestion and see how things work.

2021-11-06 14:43 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +            <TextField
can we validate email is correct? In other projects we use [react-hook-forms](https://react-hook-form.com/) to help clean up forms and validation

2021-11-06 14:44 UTC, jsw324 commented on src/components/BottomContainer/index.js
> +const BottomContainer = styled('div')({
why would you have to reorder?

2021-11-06 14:45 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +} from '@mui/material'
No reason to introduce more complexity, let's just import each component individually.

2021-11-06 14:57 UTC, imcvampire commented on src/components/BottomContainer/index.js
> +const BottomContainer = styled('div')({
Ah, no. If `atom`s are styled components, I believe we don't need to re-order if they could be changed from a child to a parent component.

2021-11-06 15:07 UTC, imcvampire commented on src/pages/VerifyConsumer/index.js
> +    if (currentPage === INFO_PAGE) {
I think we're going to send a user to step 2. After selecting a picture and confirming it (step 1), the user will be redirected to step 2 for other inputs. Moreover, having separate pages could improve readability and/or editability if each step is large enough. 

For your suggested component, I think it's suitable for small steps. In our use case, we have 5 steps in total, and each page is different. From the implementation aspect, we might have 5 render functions, and a check (`map`, `if`, `switch`, ...) to use the correct function based on the index. Seems like not an easy task. 

 If we use separate routes, the number of LoC and the complexity will be smaller, which is easier to maintain.

2021-11-08 13:24 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +    if (currentPage === INFO_PAGE) {
i meant we're never going to send a user directly to step 2 

i'm good with using separate routes, that works.

2021-11-08 14:14 UTC, jsw324 commented
This is better...i would like to recognize that i'm logged in, if possible as it's inconvenient to make a user take a new selfie each time he/she logs in to see their photos.

I'm also thinking this can be a single step - it's only 3 fields in the form and we're not verifying the upload was successfully before moving to step 2 so i don't see why this shouldn't be one screen.  I'll approve so we're not blocked but i think this would be better in a single screen.

Thoughts?

2021-11-08 20:16 UTC, imcvampire commented
> This is better...i would like to recognize that i'm logged in, if possible as it's inconvenient to make a user take a new selfie each time he/she logs in to see their photos.
> 
> I'm also thinking this can be a single step - it's only 3 fields in the form and we're not verifying the upload was successfully before moving to step 2 so i don't see why this shouldn't be one screen. I'll approve so we're not blocked but i think this would be better in a single screen.
> 
> Thoughts?

I've thought about that after some time, I think your design makes sense so I stick with it. 

> Please test this before merging as i'm getting a graphQL error as well

Yes, seems like it's an edge case. I'm checking it with Hong. 

BTW, seems like I don't have permission to merge.

2021-11-08 20:18 UTC, merged

2021-11-08 20:19 UTC, jsw324 commented
@imcvampire not sure why you can't merge - i merged for you and i'll check the settings.  

< i think your design makes sense so I stick with it.

 Are you saying you're going to move it to one screen with the image uploader and the 3 inputs? I do think that's better but we can always do it later :)