add Consumer screen
pgahq/face-finder-frontend pull request #2
Opened 2021-11-10 09:41 UTC by imcvampire

2021-11-10 15:03 UTC, jsw324 commented
@imcvampire would it be possible to provide more of a description to your PR's? Screenshots showing the screen being implemented would be _fantastic_

2021-11-10 19:39 UTC, imcvampire commented
> @imcvampire would it be possible to provide more of a description to your PR's? Screenshots showing the screen being implemented would be _fantastic_

Added. Please kindly check it!

2021-11-11 15:55 UTC, jsw324 requested changes
Small changes but overall this is fantastic!

2021-11-11 15:55 UTC, jsw324 commented on src/lib/apollo/index.js
> +      const token = window.localStorage.getItem('accessToken')
can we use [context API](https://reactjs.org/docs/context.html) to store/set this item instead of local storage?

2021-11-11 15:55 UTC, jsw324 commented on src/pages/SelectEvent/EventsSkeleton.js
> +const EventsSkeleton = () => {
🆒

2021-11-11 15:55 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +      window.localStorage.setItem('accessToken', accessToken)
[context API ](https://reactjs.org/docs/context.html)would be helpful here so we don't have to rely on local storage

2021-11-11 15:55 UTC, jsw324 commented on src/pages/ViewPhoto/ViewPhotoSkeleton.js
> +const ViewPhotoSkeleton = () => {
nice!

2021-11-11 15:55 UTC, jsw324 commented on src/pages/VerifyConsumer/index.js
> +  const resizeFile = (file) =>
should this be moved to somewhere else where it can be reused in other parts of the project?

2021-11-11 15:55 UTC, jsw324 commented on src/pages/ViewPhoto/index.js
> +  const { data, loading } = useQuery(MY_PHOTOS_IN_EVENT, {
let's make sure we have some margin/padding between photos so they don't run up against each other:

![image](https://user-images.githubusercontent.com/3531954/141328462-fe3c816f-faf0-4117-9bd4-d78b4cef8fc0.png)

2021-11-14 16:21 UTC, jsw324 approved these changes
👍

2021-11-14 16:27 UTC, jsw324 commented
@imcvampire i pushed one small change to use ["masonry" image layout ](import Grid from '@mui/material/Grid'
)instead of a Grid.  I think it looks a bit more interesting

![image](https://user-images.githubusercontent.com/3531954/141689498-efca3ad0-d42c-4e3c-8f72-4a2c2cc05b5c.png)

2021-11-14 16:29 UTC, imcvampire commented
@jsw324 Nice idea, it looks better. 
If everything is okay, feel free to merge it. I'm not authorized. 
<img width="991" alt="Screenshot 2021-11-14 at 6 29 03 pm" src="https://user-images.githubusercontent.com/9426721/141689542-556e3226-3aec-4d50-891a-7862b6563dde.png">

2021-11-15 00:54 UTC, merged